### PR TITLE
github and google analytics graphs

### PR DESCRIPTION
**Pull request by kweav**
This PR includes graphs for the github metrics

### CODE REVIEW

**Comment by kweav** [comment]
Have added web traffic overtime for the main OCS website as well as each case study and engagement metric graphs for each case study and a table with metrics for the main OCS website and pooled case studies

**Comment by kweav** [comment]
@carriewright11 the checks pass now and there's a preview!

**Comment by kweav** [comment]
Would appreciate feedback on output sizes for the tables and plots and if you'd like any adjustments for those

**Comment by carriewright11** [comment]
This looks great! I wonder if we could do a map instead of the list of countries?

**Comment by kweav** [comment]
Would love to do a map but need pointed to a resource on how you prefer to do maps :)

**Comment by carriewright11** [comment]
> Would appreciate feedback on output sizes for the tables and plots and if you'd like any adjustments for those

I noticed some of the case study names are getting cut off in the facets, maybe we could adjust to allow more of the name to fit? can maybe remove ocs-bp from names if that helps

**Comment by carriewright11** [comment]
I think we could merge this though and start a new PR on maps (I will send resources on slack)

**Comment by carriewright11** [comment]
It might be worth hiding the plots for github except the first one for now until we get more data

**Pull request merged**
